-- 外文文献库（与 lit_paper 同结构，独立存储便于按语言分流检索）
-- MySQL 8+；英文 FULLTEXT 用默认分词（不用 ngram）

CREATE TABLE IF NOT EXISTS `lit_paper_en` (
  `id`             BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
  `cnki_id`        VARCHAR(64)   DEFAULT NULL COMMENT '知网文献ID',
  `doi`            VARCHAR(200)  DEFAULT NULL COMMENT 'DOI',
  `title`          VARCHAR(500)  NOT NULL COMMENT '标题',
  `authors`        VARCHAR(1000) DEFAULT NULL COMMENT '作者',
  `organs`         VARCHAR(1000) DEFAULT NULL COMMENT '机构',
  `abstract_text`  MEDIUMTEXT    DEFAULT NULL COMMENT '英文摘要',
  `keywords`       VARCHAR(500)  DEFAULT NULL COMMENT '英文关键词',
  `title_zh`       VARCHAR(500)  DEFAULT NULL COMMENT '知网中译题名',
  `abstract_zh`    MEDIUMTEXT    DEFAULT NULL COMMENT '知网中译摘要',
  `keywords_zh`    VARCHAR(500)  DEFAULT NULL COMMENT '知网中译关键词',
  `source`         VARCHAR(1000) DEFAULT NULL COMMENT '刊名/会议文集等',
  `year`           INT           DEFAULT NULL COMMENT '年份',
  `volume`         VARCHAR(64)   DEFAULT NULL COMMENT '卷号',
  `issue`          VARCHAR(64)   DEFAULT NULL COMMENT '期号',
  `pages`          VARCHAR(100)  DEFAULT NULL COMMENT '起-止页码',
  `publisher`      VARCHAR(200)  DEFAULT NULL COMMENT '出版者',
  `publish_place`  VARCHAR(200)  DEFAULT NULL COMMENT '出版地',
  `translator`     VARCHAR(200)  DEFAULT NULL COMMENT '译者',
  `degree`         VARCHAR(100)  DEFAULT NULL COMMENT '学位类型',
  `degree_place`   VARCHAR(200)  DEFAULT NULL COMMENT '授予单位所在地',
  `patent_country` VARCHAR(100)  DEFAULT NULL COMMENT '专利国名',
  `patent_kind`    VARCHAR(100)  DEFAULT NULL COMMENT '专利文献种类',
  `patent_no`      VARCHAR(100)  DEFAULT NULL COMMENT '专利号',
  `standard_code`  VARCHAR(100)  DEFAULT NULL COMMENT '技术标准代号',
  `publish_date`   VARCHAR(64)   DEFAULT NULL COMMENT '专利/标准出版日期',
  `doc_type`       VARCHAR(10)   DEFAULT NULL COMMENT 'J/D/C/M/P/S',
  `cite_count`     INT           DEFAULT 0 COMMENT '被引次数',
  `lit_source`     VARCHAR(32)   NOT NULL DEFAULT 'CNKI' COMMENT '文献来源',
  `citation_gbt`   TEXT          DEFAULT NULL COMMENT 'GB/T 7714',
  `detail_url`     VARCHAR(1000) DEFAULT NULL COMMENT '详情URL',
  `title_hash`     CHAR(64)      DEFAULT NULL COMMENT '规范化标题哈希',
  `crawl_keyword`  VARCHAR(200)  DEFAULT NULL COMMENT '首次检索词',
  `status`         VARCHAR(20)   NOT NULL DEFAULT 'active' COMMENT 'active/incomplete',
  `crawled_at`     DATETIME      DEFAULT NULL,
  `create_time`    DATETIME      DEFAULT CURRENT_TIMESTAMP,
  `update_time`    DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_lit_paper_en_cnki_id` (`cnki_id`),
  UNIQUE KEY `uk_lit_paper_en_doi` (`doi`),
  KEY `idx_lit_paper_en_year` (`year`),
  KEY `idx_lit_paper_en_cite` (`cite_count`),
  KEY `idx_lit_paper_en_type` (`doc_type`),
  KEY `idx_lit_paper_en_title_hash_year` (`title_hash`, `year`),
  KEY `idx_lit_paper_en_status` (`status`),
  FULLTEXT KEY `ft_lit_paper_en` (`title`, `keywords`, `abstract_text`),
  FULLTEXT KEY `ft_lit_paper_en_zh` (`title_zh`, `keywords_zh`, `abstract_zh`) WITH PARSER ngram
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外文文献库主表';

CREATE TABLE IF NOT EXISTS `lit_paper_en_ref` (
  `id`         BIGINT       NOT NULL AUTO_INCREMENT,
  `paper_id`   BIGINT       NOT NULL,
  `ref_index`  INT          NOT NULL,
  `raw_text`   TEXT         NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_lit_paper_en_ref_paper` (`paper_id`, `ref_index`),
  CONSTRAINT `fk_lit_paper_en_ref_paper` FOREIGN KEY (`paper_id`) REFERENCES `lit_paper_en` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='外文文献参考文献列表';
