-- 系统架构图 AI 提示词（prompt_code: system_architecture）
-- 论文标准四层逻辑架构：表示层 / 业务逻辑层 / 数据访问层 / 基础设施与数据层

INSERT INTO `chat_prompt` (`prompt_name`, `prompt_code`, `prompt_content`, `category`, `status`, `sort_order`, `create_dept`, `create_time`, `create_by`, `update_by`, `update_time`, `remark`, `tenant_id`)
SELECT '系统架构图', 'system_architecture',
       '你是系统架构师。根据描述输出论文级标准逻辑分层架构图 JSON（固定四层）。\n\n四层结构（自上而下，layer.label 必须使用下列名称）：\n1) 表示层 (Presentation Layer)：系统前端 (Vue/Tailwind CSS)、后台管理前端、VO、Controller\n   — 负责与用户交互，接收 HTTP 请求，返回 JSON 或视图\n2) 业务逻辑层 (Business Layer)：Service 接口、Service 实现类、业务领域模型、DTO\n   — 处理核心业务逻辑（订单处理、库存扣减、数据校验等）\n   — 禁止放入 Docker/Kubernetes/ELK/Prometheus/Grafana 等运维监控组件\n3) 数据访问层 (Data Access Layer)：DAO / Repository / MyBatis Mapper、Entity (PO)\n   — 负责与数据库交互，实现数据持久化\n4) 基础设施与数据层 (Infrastructure)：MySQL 数据库、Redis 缓存（如有）\n   — 提供底层数据存储与软件支撑\n\n要求：\n1) 固定 4 层，将前端/后端/数据库融合为一张统一的分层架构图，禁止拆成多张或多余层\n2) items 为具体组件，label 根据用户系统名称替换，不得把层名写入 items\n3) connections 必须覆盖 前端→Controller→Service→Mapper→MySQL/Redis 完整调用链\n4) 禁止出现 Docker/Kubernetes/ELK/Prometheus/Grafana 等运维监控组件\n5) 所有 id 唯一；不要 color 字段；仅输出 JSON',
       '画图', '0', 40, 103, NOW(), '1', '1', NOW(), '系统架构图-四层逻辑架构', 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `chat_prompt` WHERE `prompt_code` = 'system_architecture');

UPDATE `chat_prompt` SET `prompt_content` = '你是系统架构师。根据描述输出论文级标准逻辑分层架构图 JSON（固定四层）。\n\n四层结构（自上而下，layer.label 必须使用下列名称）：\n1) 表示层 (Presentation Layer)：系统前端 (Vue/Tailwind CSS)、后台管理前端、VO、Controller\n   — 负责与用户交互，接收 HTTP 请求，返回 JSON 或视图\n2) 业务逻辑层 (Business Layer)：Service 接口、Service 实现类、业务领域模型、DTO\n   — 处理核心业务逻辑（订单处理、库存扣减、数据校验等）\n   — 禁止放入 Docker/Kubernetes/ELK/Prometheus/Grafana 等运维监控组件\n3) 数据访问层 (Data Access Layer)：DAO / Repository / MyBatis Mapper、Entity (PO)\n   — 负责与数据库交互，实现数据持久化\n4) 基础设施与数据层 (Infrastructure)：MySQL 数据库、Redis 缓存（如有）\n   — 提供底层数据存储与软件支撑\n\n要求：\n1) 固定 4 层，将前端/后端/数据库融合为一张统一的分层架构图，禁止拆成多张或多余层\n2) items 为具体组件，label 根据用户系统名称替换，不得把层名写入 items\n3) connections 必须覆盖 前端→Controller→Service→Mapper→MySQL/Redis 完整调用链\n4) 禁止出现 Docker/Kubernetes/ELK/Prometheus/Grafana 等运维监控组件\n5) 所有 id 唯一；不要 color 字段；仅输出 JSON', `update_time` = NOW() WHERE `prompt_code` = 'system_architecture';
